### ISSUE TITLE
Increase page load performance

### ISSUE THREAD

**Issue by gfairchild** [darshanbaral/aafu#7]
I just ran my website (based on the latest aafu theme) through [Google's PageSpeed Insights](https://developers.google.com/speed/pagespeed/insights/) page ([here are my results](https://developers.google.com/speed/pagespeed/insights/?url=https%3A%2F%2Fwww.gfairchild.com%2F)) and noticed that it looks like a few things could be improved. Specifically, there are some [Render-Blocking Resources](https://developers.google.com/web/tools/lighthouse/audits/blocking-resources) that are identified that might be able to be modified using the `defer` or `async` attributes, among other things.

Have you by chance looked at improving page load performance by implementing any of these suggestions?

**Comment by darshanbaral** [comment]
The https://github.com/darshanbaral/aafu/commit/4e353c33dacfa7f0acc4406c857ca9daae750daf serves bootstrap locally instead of CDN and that seems to have [improved speed for the demo](https://developers.google.com/speed/pagespeed/insights/?url=https%3A%2F%2Faafudemo.netlify.com%2F&tab=mobile). For further improvements, `font awesome` and `academicons` could be served locally too but it's already pretty fast.

**Comment by gfairchild** [comment]
Yeah, I know it's already super fast, but I just figured that there are likely a few small adjustments that can be made to make it even faster!
